import type { Metadata } from 'next';
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from '@mantine/core';
import '@mantine/core/styles.css';
import { QueryClientProvider } from '@tanstack/react-query';
import queryClient from '@/apis/queryClient';
import { Footer } from '@/components/layouts/footer';
import { Header } from '@/components/layouts/header';
import { LookbookStoreProvider } from '@/hooks/lookbook-provider';
import { THEME } from '@/shared/common/theme';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <QueryClientProvider client={queryClient}>
          <MantineProvider theme={THEME}>
            <LookbookStoreProvider>
              <Header />
              {children}
              <Footer />
            </LookbookStoreProvider>
          </MantineProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
